name: PixelMower
options:
  bundleIdPrefix: com.pixelmower
  deploymentTarget:
    iOS: "16.0"
  platforms:
    iOS: {}

targets:
  PixelMower:
    type: application
    platform: iOS
    sources:
      - path: PixelMower
    info:
      UISupportedInterfaceOrientations: [UIInterfaceOrientationPortrait]
      UISupportedInterfaceOrientations~ipad: [UIInterfaceOrientationPortrait]
      CFBundleDisplayName: "搬砖大亨"
    settings:
      base:
        SWIFT_VERSION: 5.0
        TARGETED_DEVICE_FAMILY: 1
