name: PixelMower
options:
  bundleIdPrefix: com.pixelmower
targets:
  PixelMower:
    type: application
    platform: iOS
    sources:
      - PixelMower
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.pixelmower.game
        PRODUCT_NAME: PixelMower
        EXECUTABLE_NAME: PixelMower
        GENERATE_INFOPLIST_FILE: YES
        SWIFT_VERSION: "5.0"
